#pragma once
#ifndef COMPONENTTYPE_H
#define COMPONENTTYPE_H

enum ComponentType {
	DEFAULT,
	AABB_COLLIDER_COMPONENT,
	ANIMATOR_COMPONENT,
	RIGIDBODY_COMPONENT,
	SPRITE_COMPONENT,
	CAMERA_COMPONENT
};

#endif